<a href="https://colab.research.google.com/github/roccipelaez/THCRocio/blob/main/19_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
a= np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [4]:
arr= np.array([1,2,3,4])
print(arr[0])

1


In [5]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("segundo elemento de la primer fila es: ",arr[0,1])

segundo elemento de la primer fila es:  2


In [6]:
#Suma de elementos de matriz
A=[[1,1,1],[1,1,1],[1,1,1]]
suma=0
for i in  range(len(A)):
  for j in range(len(A)):
     suma+=A[i][j]
print(suma)

9


In [7]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
A= arr[0]+arr[1]+arr[2]
print(A[0]+A[1]+A[2])


45


In [16]:
#Producto escalar por renglones (numpy)
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
A= arr[0]+arr[1]+arr[2]
print(arr[1])


[4 5 6]


In [17]:
def ProdPunto(a,b):
  PP=0.0
  for i in range(len(a)):
    PP=PP+a[i]+b[i]
  return PP


In [23]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([[1,1,1],[1,1,1],[1,1,1]])
PP_por_reng=np.array([0,0,0])
PP_por_col=np.array([0,0,0])


In [19]:
for i in range(len(arr2)):
  PP_por_reng[i]=ProdPunto(arr2[i],arr3[i])

PP_por_reng

array([ 9, 18, 27])

In [20]:
def AgarraCol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])
  return np.array(nuevo)

In [21]:
col1=AgarraCol(arr2,0)
col1


array([1, 4, 7])

In [24]:
for i in range(len(arr2)):
  PP_por_col[i]=ProdPunto(AgarraCol(arr2,i),AgarraCol(arr3,i))
PP_por_col

array([15, 18, 21])